# Generated by Django 3.0.5 on 2020-05-24 19:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('prescription', models.CharField(max_length=255)),
                ('diseases', models.CharField(max_length=150)),
                ('doctor_name', models.ForeignKey(limit_choices_to={'groups__name': 'Doctors'}, on_delete=django.db.models.deletion.CASCADE, related_name='Doctor+', to=settings.AUTH_USER_MODEL)),
                ('patient_name', models.ForeignKey(limit_choices_to={'groups__name': 'Patients'}, on_delete=django.db.models.deletion.CASCADE, related_name='Patient+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
