# Generated by Django 3.0.5 on 2020-05-25 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0004_auto_20200525_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='medical_reports',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
