# Generated by Django 3.0.5 on 2020-05-25 14:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('department', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Outstanding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('Total', models.CharField(max_length=20, null=True)),
                ('paid', models.CharField(max_length=20, null=True)),
                ('outstanding', models.CharField(max_length=11, null=True)),
                ('patient_name', models.ForeignKey(limit_choices_to={'groups__name': 'Patients'}, on_delete=django.db.models.deletion.CASCADE, related_name='Patient++', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
